[tools]
python = "3.14.0"
uv = "0.9.16"

[env]
_.file = [".env"]

[tasks.sync]
run = "uv sync"

[tasks.up]
run = "docker compose up"

[tasks.down]
run = "docker compose down"

[tasks.script]
run = "uv run scripts/insert_sample_data.py"

[tasks.test]
run = "uv run pytest"

[tasks.format]
run = "uv run ruff format"