[project]
name = "elastic-search-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "elasticsearch>=9.2.0",
    "starlette>=0.50.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]
